# Generated by Django 3.2 on 2021-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('albums', models.ManyToManyField(to='napio.AlbumInfo')),
                ('artists', models.ManyToManyField(to='napio.ArtistInfo')),
            ],
        ),
    ]
